### ISSUE TITLE
Cracked WPA hashes skipped

### ISSUE THREAD

**Issue by beecushman** [s3inlc/hashtopolis#602]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
Hashtopolis: 0.11.0 commit 41d456b branch master

- Current Client version
0.6.0 stable

- Your current Hashcat version
v5.1.0-1673-g5f57ab3

- The exact task command you are trying to run.
#HL# wonder-list-sorted-uniq.txt.gz

- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

```
[2020-02-12 19:53:53,973] [DEBUG] Sending 1 cracks...
[2020-02-12 19:53:53,973] [DEBUG] {'action': 'sendProgress', 'chunkId': 8, 'gpuUtil': [83], 'keyspaceProgress': 4751459, 'state': 2, 'relativeProgress': 9327, 'gpuTemp': [75], 'cracks': [['98184655684b:638ea391e3ff:MyS03iFiWmurtcep-2G', 'yelteertswol086', '79630347565627473777f6c6c65836', '173141']], 'speed': 452242, 'token': 'UMT4qmhBXd'}
[2020-02-12 19:53:54,046] [DEBUG] http://8.8.8.8:80 "POST /api/server.php HTTP/1.1" 200 80
[2020-02-12 19:53:54,047] [DEBUG] b'{"action":"sendProgress","response":"SUCCESS","cracked":0,"skipped":1,"zaps":[]}'
[2020-02-12 19:53:54,047] [INFO ] Progress: 93.27% Speed: 452.24kH/s Cracks: 1 Accepted: 0 Skips: 1 Zaps: 0
[2020-02-12 19:53:58,996] [DEBUG] STATUS        3      SPEED  453686  1000    EXEC_RUNTIME    11.417434      CURKU  0      PROGRESS        109182976      0      RECHASH 1      128    RECSALT 0      68      TEMP    68      REJECTED        0      UTIL    15
```

**Describe your problem in as much detail as possible " It's broke " is not a description.**

I have a WPA/WPA2 hashlist (mode 2500) uploaded in HCCAPX format. It's a combined file (using cat) and Hashtopolis recognizes the number of hashes: 0.00% (0 / 131).

I have a wordlist, wonder-list-sorted-uniq.txt.gz, and then I have created a task to associate the two. I'm not doing any preprocessing or anything fancy, just a plain wordlist attack. When running the task, debug shows that Hashcat is able to crack some of the hashes, I _believe_ Hashtopolis is recognizing this as it shows an entry for "Cracks:", but it also has the same value for "Skips:" so for instance it will have 1 for both.

The outfile looks similar to this:

```
98184655684b:638ea391e3ff:MyS03iFiWmurtcep-2G yelteertswol086 79630347565627473777f6c6c65836 173141
```

I created a test NTLM hash just to test it, and the NTLM hash cracks and actually gets saved to the Hashtopolis database, and shows up in the web app. So I can confirm that part at least is working for me.

The hashfile can be found here https://oshi.at/sZzgSv with yellowstreet086 as the plaintext. The hash type for the provided information is 2500. The hash lists do not have the `salted` flag checked.

I've also noticed the same behavior for the hash type 16800 which is WPA-PMKID-PBKDF2. I assume they are both related, but I have not confirmed the outfile. I can run through a task and provide that information as well.

**Comment by s3inlc** [comment]
I was able to confirm your issue. It is not exactly a bug, but it is due to the fact that hashcat somewhere between the 5.1.0 release and the current beta changed the way how a found WPA (-m 2500) is printed. 
I now changed the server to be able to handle both variants for WPA, could you please test if that also fixes your issue with the mode 2500? (code is on branch `issue/wpa`).

Regarding your second statement, about mode 16800, I doubt that it's exactly the same issue, but it's possible that there is an issue as well. If you could provide some more details and an example (as you did for 2500), that would help a lot.

**Comment by s3inlc** [comment]
nvm, regarding mode 16800 there are some more serious problems right now I'll have to discuss with atom. Don't bother creating an example etc., I'll do a separate issue for this and then do a separate fix later. 
Please report back if my changes in the branch fix your issue with mode 2500.

**Comment by beecushman** [comment]
Great, I tested the branch and it seems to be working as expected for hccapx/2500 :)

I created an example for pmkid/16800 before reading the latest update, but it sounds you have awareness of a related issue. If it's of benefit in the future let me know I can provide it.

Otherwise, I believe the issues that surfaced with the formatting have been addressed for hccapx/2500. Thanks again for the great work!

![image](https://user-images.githubusercontent.com/20655306/74565265-b5c21080-4f25-11ea-92fa-a4f50e232701.png)

**Comment by s3inlc** [comment]
Thanks for the feedback. I'll merge the changes for mode 2500 into master now and then care about getting pmkid working.

**Comment by geronimo23** [comment]
I still have this problem with hastopolis 0.12.0 and hashcat 5.1.0. When I'm running `python3 hastopolis.zip --debug` on my agent I clearly see the cracked WPA password. But the server does not retrieve the results. Can someone help, please?

**Comment by geronimo23** [comment]
nevermind, I solved it by using the latest beta https://hashcat.net/beta/
